### ISSUE TITLE
 'generator' object is not subscriptable

### ISSUE THREAD

**Issue by beanels01** [HaeImCH/DiscordBot-ChatGPT#2]
`
[INFO] [13:55:59] 正在傳送訊息給OpenAI
==============================[ERROR]==============================
[ERROR] [13:55:59] 傳送訊息給OpenAI失敗 -- Error
[ERROR] [13:55:59] 'generator' object is not subscriptable
`
想請問這部分可能是哪部分元件出問題呢？感謝

**Comment by miralee218** [comment]
I got same issue

**Comment by HaeImCH** [comment]
sorry for slow update! 
this issue should be fixed.
